#! ---------------------------------------------------------------
#! ObsidiaNext Theme for Hexo
#! ---------------------------------------------------------------
#! Designed & Coded By TriDiamond
#! ---------------------------------------------------------------

#! ---------------------------------------------------------------
#! Site Configs
#！ @docs https://obsidianext.tridiamond.tech/guide/configuration.html
#! ---------------------------------------------------------------
site:
  subtitle: TriDiamond's Blog
  author: 三钻
  nick: TriDiamond
  description: 一位正在重塑知识的技术人 <br /> @ <b>公众号：技术银河</b>
  language: cn
  multi_language: true
  logo: https://img-blog.csdnimg.cn/20210313122054101.png
  avatar: https://img-blog.csdnimg.cn/20210313122054101.png
  beian: ''

#! ---------------------------------------------------------------
#! Authors Configs
#！ @docs https://obsidianext.tridiamond.tech/guide/authors.html
#! ---------------------------------------------------------------
authors:
  tom:
    name: Tom Cat
    avatar: https://img-blog.csdnimg.cn/20210313122054101.png
    link: https://github.com/TriDiamond
  John:
    name: John
    avatar: https://img-blog.csdnimg.cn/20210313122054101.png
    link: https://github.com/TriDiamond

#! ---------------------------------------------------------------
#! Menu Configs
#！ @docs https://obsidianext.tridiamond.tech/guide/menu.html
#! ---------------------------------------------------------------
menu:
  About: true
  Tags: true
  Archives: true
  # Custom menus
  message-board:
    name: 'MessageBoard'
    i18n: 'message-board'
    path: '/page/message-board'
  # frontend-tutorials:
  #   name: 'Tutorials'
  #   path: 'https://github.com/tridiamond'
  projects:
    name: 'Projects' # if no i18n is set, this will be used as menu name
    #i18n: 'project' # i18n need to be configured in src/locales/language/en.json or cn.json
    path: # Will not be used if there are sub-menus
    children:
      obsidian:
        name: 'Obsidian Theme'
        path: 'https://github.com/tridiamond'

#! ---------------------------------------------------------------
#! Theme Config
#! @docs https://obsidianext.tridiamond.tech/guide/theme.html
#! ---------------------------------------------------------------
theme:
  # Theme dark mode
  # "enable" can be set as:
  #   true: force default to be dark-mode
  #   false: force default to be light-mode
  #   'auto': adapt to system's mode
  dark_mode: true

  # Gradient colors used for the theme
  # This consist of 3 gradient colors
  # each can be customized
  gradient:
    color_1: '#24c6dc'
    color_2: '#5433ff'
    color_3: '#ff0099'

#! ---------------------------------------------------------------
#! Social Configs
#! @docs https://obsidianext.tridiamond.tech/guide/social.html
#! ---------------------------------------------------------------
socials:
  github: 'https://github.com/TriDiamond'
  twitter: ''
  stackoverflow: ''
  wechat: ''
  qq: ''
  weibo: 'https://weibo.com/u/7318914058'
  zhifu: 'https://www.zhihu.com/people/tridiamond'
  csdn: 'https://blog.csdn.net/TriDiamond6'
  juejin: 'https://juejin.cn/user/1873223546578589'

#! ---------------------------------------------------------------
#! Site Meta Configs
#! @docs https://obsidianext.tridiamond.tech/guide/theme.html
#! ---------------------------------------------------------------
site_meta:
  # CDN switcher
  # -> can be `cn` or `en`
  # -> cn will use China's cdn
  # -> en will use international cdn
  cdn: en

#! ---------------------------------------------------------------
#! Plugins
#! ---------------------------------------------------------------

# For local development only!
gitalk:
  enable: true
  autoExpand: true
  clientID: ''
  clientSecret: ''
  repo: 'dev-blog-comments'
  owner: 'TriDiamond'
  admin: ['TriDiamond']
  # Ensure uniqueness and length less than 50
  # If using 'pathname' ensure length is less than 50 characters
  # or use 'uid' instead for better compatibility (If you use other theme before, this will lost your comments)
  id: uid
  # Facebook-like distraction
  language: en
  distractionFreeMode: true
  recentComment: true

# Valine comment plugin (recommended!)
# see https://valine.js.org/quickstart.html
valine:
  enable: false
  app_id:
  app_key:
  avatar: ''
  placeholder: Leave your thoughts behind~
  visitor: true
  lang: en
  meta: ['nick', 'mail']
  admin: 'TriDiamond'
  recentComment: true

# Enable Busuanzi statistic plugin
# see http://ibruce.info/2015/04/04/busuanzi/
busuanzi:
  enable: true
